### ISSUE TITLE
Cannot edit time-off type

### ISSUE THREAD

**Issue by freshelle** [GeneralMagicio/companybrain#24]
@tomislavmamic 

I cannot edit time-off time on my own records, and also for others. 
<img width="735" alt="image" src="https://user-images.githubusercontent.com/86718721/205638279-73492a33-1f30-49a7-b84d-542e8fb83c6b.png">

It would be nice if I can edit other's time-off type as well. For example, this one, it's already in the description it is paid, but member erroneously tagged it as unpaid. I should be able to edit it on my end.

<img width="663" alt="image" src="https://user-images.githubusercontent.com/86718721/205638474-64e3a8be-776c-450b-94cf-3d93dbe4e94d.png">

**Comment by tomislavmamic** [comment]
Try now

**Comment by freshelle** [comment]
Thanks @tomislavmamic. I can edit now, but seems like it didn't reflect in the totals table

<img width="340" alt="image" src="https://user-images.githubusercontent.com/86718721/205644692-88ae5f89-c917-4ae4-8a21-286ea2b7248a.png">

**Comment by tomislavmamic** [comment]
Did it update now?

**Comment by freshelle** [comment]
Yes, thank you!
