### ISSUE TITLE
Cannot filter per Org

### ISSUE THREAD

**Issue by freshelle** [GeneralMagicio/companybrain#28]
I'm trying to get the total hours for only Giveth WGs but cant seem to do so

https://user-images.githubusercontent.com/86718721/229233043-1ffba35f-6f46-41c1-958c-90d7c9dffa95.mov

**Comment by freshelle** [comment]
https://user-images.githubusercontent.com/86718721/229233495-c64b7326-9e0b-4ddf-90d6-b558b1962653.mov

**Comment by tomislavmamic** [comment]
Just added Supplier option to the filter. This will filter by which org billed the work
Let me know if this is what you needed


<img width="523" alt="CleanShot 2023-04-01 at 11 00 17@2x" src="https://user-images.githubusercontent.com/15949483/229276595-095a3c12-9e89-415d-a77c-8ad81a880f9e.png">

**Comment by freshelle** [comment]
What's the difference with works for? This is confusing
