### ISSUE TITLE
GM Company Brain

### ISSUE THREAD

**Issue by markoprljic** [GeneralMagicio/companybrain#6]

**Comment by ahmadabugosh** [comment]
We had a meeting today with @tomislavmamic and he's working on a prototype for us using Coda. On a high level we want:

- HR Pipeline (knowing who is in a trial month, who is full time, part time etc)
- Reminders on important HR tasks (buddy reviews, vacation days etc)
- Public Database (so anyone at the organization can see who is working on what)
- Capacity % hours (for everyone on the team, including the project they're working on
- Billing clients, who worked on what (how many hours per person)
- Payroll
